### PR TITLE
fix: Warning: mkdir(): File exists in FileHelper.php on line 64

### PR DESCRIPTION
**Pull request by thenotsoft**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

### CODE REVIEW

**Comment by samdark** [comment]
How to reproduce it?

**Comment by thenotsoft** [comment]
Delete assets, then press f5 and get this error

image

**Comment by samdark** [comment]
OK. The change is not correct but that's good that you've raised the issue. What should be done:

1. We can't rely on try-catch. The code was assumed to work with Yii 2 where warnings/errors are always converted to exceptions. Instead we need to use
  ```php
  set_error_handler(static function (int $errorNumber, string $errorString, string $errorFile, int $errorLine) {
      throw new ErrorException($errorString, $errorNumber, 0, $errorFile, $errorLine);
  });
  // something
  restore_error_handler();
   ```
2. We should avoid creating directory if it exists but with an extra check at the very beginning of the method.
3. The idea of original code that you're changing is "create a directory then check if it's there".

**Comment by thenotsoft** [comment]
Why do ```is_dir``` after ```mkdir```? If mkdir doesn't create folder it will return ```false```.

**Comment by samdark** [comment]
Right. Maybe there's an edge case but out of my head, I don't remember why it was made like that.

**Comment by samdark** [comment]
Clsoing in favor of https://github.com/yiisoft/files/pull/41

**Pull request closed without merging**
